### ISSUE TITLE
Adding a new question to a Block that is already been used does not work

### ISSUE THREAD

**Issue by mzeinstra** [diligentsearch/diligentsearch-website#61]
Adding a question to a block that is already being used does not work.

After adding the question, saving and reloading the page an empty question appears.

![image](https://cloud.githubusercontent.com/assets/5627431/23258549/0cad8ec0-f9c9-11e6-9eaa-8eac53ce5293.png)

**Comment by mzeinstra** [comment]
Additionally.

Adding a question to a block, saving and re-opening the block gives a list of empty questions additionally to existing questions.
![image](https://cloud.githubusercontent.com/assets/5627431/23258640/62b61a08-f9c9-11e6-977a-72294224687d.png)

**Comment by arnaud-brun** [comment]
PB #1 : You can add an already selected question now. Besides, a bunch of empty fields will be automatically ignored on save.

PB #2 : Bug due to a bad behavior of the click event on the list element. Several clicks were bound to the same element, so that 1 click triggered several modal loading.

Those problems should be fixed now.
